stages:
    - test

variables:
    APPLICATION_NAME: astarte_rpc

mix:test-coverage:
    stage: test
    image: elixir:1.10.1
    services:
        - rabbitmq:3.8.3-rc.1
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - deps
            - _build
    before_script:
        - mix local.hex --force
        - mix local.rebar
        - mix deps.get
    script:
        - mix format --check-formatted
        - mix coveralls

mix:test-dialyzer:
    stage: test
    image: elixir:1.10.1
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - deps
            - _build
            - dialyzer_cache
    before_script:
        - mix local.hex --force
        - mix local.rebar
        - export MIX_ENV=ci
        - mix deps.get
    script:
        # TODO: we do this until we fix all dialyzer errors to force a CI success, so that plts get cached
        - mix dialyzer || echo "Done"
