stages:
    - test

variables:
    APPLICATION_NAME: astarte_rpc

mix:test-coverage:
    stage: test
    image: elixir:1.8.1
    services:
        - rabbitmq:3.7.15
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - deps
            - _build
    before_script:
        - mix local.hex --force
        - mix local.rebar
        - mix deps.get
    script:
        - mix format --check-formatted
        - mix coveralls
