stages:
    - build
    - deploy

before_script:
    - mix local.hex --force
    - mix local.rebar

variables:
    APPLICATION_NAME: astarte_rpc

mix:test-ci:
    image: elixir:1.6.5
    services:
        - rabbitmq:3.6
    stage: build
    script:
        - export MIX_ENV=test
        - mix deps.get
        - mix deps.compile
        - mix compile
        - mix coveralls
    except:
        - branches@Astarte-NG/astarte_rpc

mix:build:
    image: elixir:1.6.5
    services:
        - rabbitmq:3.6
    stage: build
    script:
        - export MIX_ENV=test
        - mix deps.get
        - mix deps.compile
        - mix compile
        - mix coveralls
        - export MIX_ENV=dev
        - mix release
    only:
        - master@Astarte-NG/astarte_rpc

mix:release-build:
    image: elixir:1.6.5
    services:
        - rabbitmq:3.6
    stage: build
    script:
        - export MIX_ENV=test
        - mix deps.get
        - mix deps.compile
        - mix compile
        - mix coveralls
        - export MIX_ENV=prod
        - mix release
    only:
        - tags@Astarte-NG/astarte_rpc
